# Generated by Django 5.2.17 on 2026-09-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_is_discount_product_on_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url_origin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
