# Generated by Django 5.2.17 on 2026-09-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='name',
            field=models.CharField(default='Gogo Gaga', max_length=100),
        ),
    ]
